### PR TITLE
fix: ".git" matching

### PR DESCRIPTION
**Pull request by ShuguangSun**
"." should be "\\\."

### CODE REVIEW

**Comment by cjohansson** [comment]
Can you describe the error? I can't reproduce any issue with ".git/" instead of "\\\\.git/"

**Comment by ShuguangSun** [comment]
If I have a folder named agit then it will be matched by ".git/". However, I suppose we just want to filter "\\.git/", the git repo, itself.

**Comment by cjohansson** [comment]
Yes you are right, have you signed the FSF papers? I wonder if merging your commit affects the license of my project..

**Comment by ShuguangSun** [comment]
I have signed.

**Comment by cjohansson** [comment]
Alright, can you please escape the dots in `.dir-locals.el` as well please? Currently it could match other stuff, it should be `\\\.dir-locals\\\.el`

**Pull request merged**
